query sellerItemsQuery(
  $sellerIds: ID!
  $tagIds: [ID]
  $sortBy: CatalogItemSortByField
  $sortByPriceCurrencyCode: String
  $sortOrder: SortOrder
) {
  sellerCatalogItems(
    sellerIds: [$sellerIds]
    tagIds: $tagIds
    first: 20
    sortBy: $sortBy
    sortByPriceCurrencyCode: $sortByPriceCurrencyCode
    sortOrder: $sortOrder
  ) {
    totalCount
    pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
      __typename
    }
    edges {
      cursor
      node {
        _id
        ... on CatalogItemProduct {
          product {
            _id
            title
            slug
            description
            vendor
            tags {
              nodes {
                name
              }
            }
            productId
            variants {
              pricing {
                compareAtPrice {
                  displayAmount
                  __typename
                }
                currency {
                  code
                  __typename
                }
                displayPrice
                minPrice
                maxPrice
                __typename
              }
              _id
              variantId
              optionTitle
              options {
                _id
                __typename
              }
              __typename
            }
            isLowQuantity
            isSoldOut
            isBackorder
            tagIds
            metafields {
              description
              key
              namespace
              scope
              value
              valueType
              __typename
            }
            shop {
              currency {
                code
                __typename
              }
              __typename
            }
            media {
              URLs {
                large
                __typename
              }
              __typename
            }
            primaryImage {
              URLs {
                thumbnail
                small
                medium
                large
                __typename
              }
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
